# Generated by Django 3.2 on 2021-06-03 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20200823_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='creation_date',
            field=models.CharField(default=datetime.datetime(2021, 6, 3, 18, 23, 35, 396275), max_length=100, verbose_name='Date'),
        ),
    ]
